"control": ""
0: ["pagedown", 1]         # Right
1: ["pageup", 1]           # Left
2: null                    # Center (초기화)
3: ["up", 5]               # Left_Close
4: ["down", 5]             # Right_Close
5: ["ctrl+\\", 1]          # Close