"control": "pdf"
0: [["pagedown", 1], ["down", 5]]       # Right
1: [["pageup", 1], ["up", 5]]           # Left
2: null                                 # Center (초기화)
3: null                                 # Left_Close
4: null                                 # Right_Close
5: [["ctrl+\\", 1]]                     # Close