"control": "pdf"
0: [["pagedown", 1], ["down", 2]]       # Right
1: [["pageup", 1], ["up", 2]]           # Left
2: null                                 # Center (초기화)
3: [["ctrl+\\", 1], ["ctrl+\\", 1]]     # Left_Close
4: [["ctrl+\\", 1], ["ctrl+\\", 1]]     # Right_Close
